{{- $dbCreateSecret := .Values.postgres.service.createConductorRoleSecret -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "service")  }}
      {{- if (hasKey .Values.global.postgres.service "createConductorRoleSecret")  }}
        {{- $dbCreateSecret = .Values.global.postgres.service.createConductorRoleSecret -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $dbCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-conductor-pg-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.conductorRoleUsername }}
  password: {{ .Values.postgres.service.conductorRolePassword }}
{{- end }}
