{{- $minioCreateSecret := .Values.minio.service.createSecret -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "minio")  }}
    {{- if (hasKey .Values.global.minio "service")  }}
      {{- if (hasKey .Values.global.minio.service "createSecret")  }}
        {{- $minioCreateSecret = .Values.global.minio.service.createSecret -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $minioCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-conductor-minio-secret
type: Opaque
data:
  access_key_id: {{ .Values.minio.service.accessKeyId }}
  secret_access_key: {{ .Values.minio.service.secretAccessKey }}
{{- end }}
