{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.singleNamespace }}
kind: RoleBinding
{{ else }}
kind: ClusterRoleBinding
{{- end }}
metadata:
  name: {{ include "local-path-provisioner.fullname" . }}
  {{- if .Values.singleNamespace }}
  namespace: {{ .Release.Namespace | quote }}
  {{- end }}
  labels:
{{ include "local-path-provisioner.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if .Values.singleNamespace }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ template "local-path-provisioner.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "local-path-provisioner.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
