{{- $migrationEnabled := .Values.postgres.migration.enabled -}}
{{- $migrationServiceAccount := .Values.postgres.migration.serviceAccount -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "migration")  }}
      {{- if (hasKey .Values.global.postgres.migration "enabled")  }}
        {{- $migrationEnabled = .Values.global.postgres.migration.enabled -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.migration "bundleServiceAccount")  }}
        {{- $migrationServiceAccount = .Values.global.postgres.migration.bundleServiceAccount -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $migrationEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $migrationServiceAccount }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $migrationServiceAccount }}-migration-reader
rules:
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - replicationcontrollers
  - replicasets
  - podtemplates
  - podsecuritypolicies
  - pods
  - pods/log
  - pods/exec
  - podpreset
  - poddisruptionbudget
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - endpoints
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - configmaps
  - namespaces
  - events
  - secrets
  verbs:
  - create
  - get
  - watch
  - delete
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $migrationServiceAccount }}-migration-reader
subjects:
- kind: ServiceAccount
  name: {{ $migrationServiceAccount }}
roleRef:
  kind: Role
  name: {{ $migrationServiceAccount }}-migration-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}
