{{- if .Values.dbMigration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
     {{- include "swoop-bundle.labels" . | nindent 6 }}
  name: "{{ .Values.dbMigration.jobName }}-{{ .Values.dbMigration.version }}"
spec:
  template:
    metadata:
      name: "{{ .Values.dbMigration.jobName }}-{{ .Values.dbMigration.version }}"
    spec:
      containers:
      - name: db-migration-job
        image:  quay.io/element84/swoop-db # replace with test cont
        command: ["python", "/opt/swoop/db/scripts/run-migration-job.py"]
        env:
        - name: PGHOST
          value: "{{.Values.postgres.service.name}}.{{.Values.dbMigration.namespace}}"
        - name: PGUSER
          value: {{.Values.postgres.service.migrationRole}}
        - name: PGPORT
          value: {{.Values.postgres.service.targetPort | quote}}
        - name: PGDATABASE
          value: {{.Values.postgres.service.dbName}}
        - name: ACTION
          value: {{.Values.dbMigration.action}}
        - name: VERSION
          value: {{.Values.dbMigration.version | quote}}
        - name: NO_WAIT
          value: {{.Values.dbMigration.no_wait | quote}}
          resources:
            requests:
              cpu: 1
              memory: "200Mi"
      restartPolicy: Never
{{- end }}
