{{- if .Values.global.postgres.service.createConductorRoleSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-bundle-pg-conductor-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.conductorRoleUsername }}
  password: {{ .Values.global.postgres.service.conductorRolePassword }}
{{- end }}
