{{- if .Values.global.postgres.service.createOwnerRoleSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-bundle-pg-owner-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.ownerRoleUsername }}
  password: {{ .Values.global.postgres.service.ownerRolePassword }}
{{- end }}
