apiVersion: v1
kind: Secret
metadata:
  name: swoop-api-pg-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.apiRoleUsername }}
  password: {{ .Values.global.postgres.service.apiRolePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: swoop-caboose-pg-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.cabooseRoleUsername }}
  password: {{ .Values.global.postgres.service.cabooseRolePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: swoop-conductor-pg-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.conductorRoleUsername }}
  password: {{ .Values.global.postgres.service.conductorRolePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: swoop-owner-pg-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.ownerRoleUsername }}
  password: {{ .Values.global.postgres.service.ownerRolePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: swoop-bundle-minio-secret
type: Opaque
data:
  access_key_id: {{ .Values.global.minio.service.accessKeyId }}
  secret_access_key: {{ .Values.global.minio.service.secretAccessKey }}
