{{- if .Values.global.postgres.service.createCabooseRoleSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-bundle-pg-caboose-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.cabooseRoleUsername }}
  password: {{ .Values.global.postgres.service.cabooseRolePassword }}
{{- end }}
