{{- if .Values.global.swoop.caboose.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
     {{- include "swoop-bundle.labels" . | nindent 6 }}
  name: "wait-for-swoop-caboose-{{ .Values.global.postgres.migration.version }}"
spec:
  template:
    metadata:
      name: "wait-for-swoop-caboose-{{ .Values.global.postgres.migration.version }}"
    spec:
      serviceAccountName: {{ .Values.global.swoop.bundle.serviceAccount }}
      containers:
        - name: wait-for-swoop-caboose-ready
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          imagePullPolicy: {{ .Values.global.postgres.migration.imagePullPolicy }}
          args:
            - "service"
            - "-lapp=swoop-caboose"
      restartPolicy: Never
{{- end }}
