{{- if .Values.global.postgres.service.createApiRoleSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-bundle-pg-api-secret
type: Opaque
data:
  username: {{ .Values.global.postgres.service.apiRoleUsername }}
  password: {{ .Values.global.postgres.service.apiRolePassword }}
{{- end }}
