{{- if .Values.global.minio.service.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-bundle-minio-secret
type: Opaque
data:
  access_key_id: {{ .Values.global.minio.service.accessKeyId }}
  secret_access_key: {{ .Values.global.minio.service.secretAccessKey }}
{{- end }}
