{{- if .Values.dbMigration.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  labels:
     {{- include "swoop-bundle.labels" . | nindent 6 }}
  name: "{{ .Values.dbMigration.jobName }}-{{ .Values.dbMigration.version }}"
spec:
  template:
    metadata:
      name: "{{ .Values.dbMigration.jobName }}-{{ .Values.dbMigration.version }}"
    spec:
      containers:
      - name: db-migration-job # Replace with DB migration job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        args: ["10s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
      restartPolicy: Never
{{- end }}
