# Default values for swoop-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

jobName: db-initialization
version: 8
namespace: default
serviceAccount: swoop-db-init
imagePullPolicy: Always

postgres:
  image:
    repository: quay.io/element84/swoop-db
    tag: latest
  service:
    port: 5432
    name: postgres
    dbName: swoop
    dbUser: cG9zdGdyZXM=
    dbPassword: cGFzc3dvcmQ=
    dbAdminUsernameSecret:
      name: pg-admin-role-secret
      key: username
    dbAdminPasswordSecret:
      name: pg-admin-role-secret
      key: password
    ownerRoleUsername: dXNlcl9vd25lcg==
    ownerRolePassword: cGFzc19vd25lcg==
    ownerRoleUsernameSecret:
      name: pg-owner-role-secret
      key: username
    ownerRolePasswordSecret:
      name: pg-owner-role-secret
      key: password
    apiRoleUsername: dXNlcl9hcGk=
    apiRolePassword: cGFzc19hcGk=
    apiRoleUsernameSecret:
      name: pg-api-role-secret
      key: username
    apiRolePasswordSecret:
      name: pg-api-role-secret
      key: password
    cabooseRoleUsername: dXNlcl9jYWJvb3Nl
    cabooseRolePassword: cGFzc19jYWJvb3Nl
    cabooseRoleUsernameSecret:
      name: pg-caboose-role-secret
      key: username
    cabooseRolePasswordSecret:
      name: pg-caboose-role-secret
      key: password
    conductorRoleUsername: dXNlcl9jb25kdWN0b3I=
    conductorRolePassword: cGFzc19jb25kdWN0b3I=
    conductorRoleUsernameSecret:
      name: pg-conductor-role-secret
      key: username
    conductorRolePasswordSecret:
      name: pg-conductor-role-secret
      key: password
