# Default values for swoop-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

postgres:
  image:
    repository: quay.io/element84/swoop-db
    tag: latest
  service:
    port: 5432
    name: postgres
    dbName: swoop
    dbHost: postgres.default
    dbUser: cG9zdGdyZXM=
    dbPassword: cGFzc3dvcmQ=
    createDBAdminSecret: true
    dbAdminUsernameSecret:
      name: pg-admin-role-secret
      key: username
    dbAdminPasswordSecret:
      name: pg-admin-role-secret
      key: password
    createOwnerRoleSecret: true
    ownerRoleUsername: c3dvb3A=
    ownerRolePassword: cGFzc19vd25lcg==
    ownerRoleUsernameSecret:
      name: pg-owner-role-secret
      key: username
    ownerRolePasswordSecret:
      name: pg-owner-role-secret
      key: password
    createApiRoleSecret: true
    apiRoleUsername: c3dvb3BfYXBp
    apiRolePassword: cGFzc19hcGk=
    apiRoleUsernameSecret:
      name: pg-api-role-secret
      key: username
    apiRolePasswordSecret:
      name: pg-api-role-secret
      key: password
    createCabooseRoleSecret: true
    cabooseRoleUsername: c3dvb3BfY2Fib29zZQ==
    cabooseRolePassword: cGFzc19jYWJvb3Nl
    cabooseRoleUsernameSecret:
      name: pg-caboose-role-secret
      key: username
    cabooseRolePasswordSecret:
      name: pg-caboose-role-secret
      key: password
    createConductorRoleSecret: true
    conductorRoleUsername: c3dvb3BfY29uZHVjdG9y
    conductorRolePassword: cGFzc19jb25kdWN0b3I=
    conductorRoleUsernameSecret:
      name: pg-conductor-role-secret
      key: username
    conductorRolePasswordSecret:
      name: pg-conductor-role-secret
      key: password
  migration:
    enabled: true
    imagePullPolicy: Always
    jobName: migration-job
    version: 8
    no_wait: false
    rollback: false
    image:
      repository: quay.io/element84/swoop-db
      tag: latest

service:
  serviceAccount: swoop-db-init
  name: db-initialization
