# Default values for stac-fastapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

pgStac:
  image:
    repository: ghcr.io/stac-utils/pgstac
    tag: v0.7.1
  container:
    port: 5432
  service:
    port: 5439
    targetPort: 5432
    name: pgstac
  deployment:
    name: pgstac
  replicaCount: 1

stacFastApi:
  image:
    repository: ghcr.io/stac-utils/stac-fastapi
    tag: main-pgstac
  container:
    port: 8080
  service:
    port: 8080
    targetPort: 8080
    name: stac-fastapi-pgstac
  deployment:
    name: stac-fastapi-pgstac
  replicaCount: 1