# Default values for stac-fastapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

local-path-provisioner:
  enabled: true
  storageClass:
    provisionerName: filmdrop.io/local-pgstac-path-provisioner
    name: local-path-class-pgstac

pgStac:
  enabled: true
  image:
    repository: ghcr.io/stac-utils/pgstac
    tag: v0.7.10
  container:
    port: 5432
  service:
    port: 5439
    targetPort: 5432
    name: pgstac
  deployment:
    name: pgstac
  createPgStacSecret: true
  userNameSecret:
    name: stac-fastapi-secret
    key: username
  passwordSecret:
    name: stac-fastapi-secret
    key: password
  dbUser: dXNlcm5hbWU=
  dbPassword: cGFzc3dvcmQ=
  dbName: postgis
  dbHost: pgstac.default
  storage:
    size: 1Gi
    volumeBindingMode: WaitForFirstConsumer
    provisioner: filmdrop.io/local-pgstac-path-provisioner
    retainPersistentVolume: true
    storageClassName: pgstac-retain
  replicaCount: 1

stacFastApi:
  image:
    repository: ghcr.io/stac-utils/stac-fastapi-pgstac
    tag: main
  container:
    port: 8080
  service:
    port: 8080
    targetPort: 8080
    name: stac-fastapi-pgstac
    serviceAccount: stac-fastapi-pgstac
  deployment:
    name: stac-fastapi-pgstac
  replicaCount: 1
