nameOverride: ""
fullnameOverride: ""

s3:
  createSecret: true
  accessKeyId: YWNjZXNza2V5aWQ=
  secretAccessKey: c2VjcmV0YWNjZXNza2V5
  region: cmVnaW9u
  data_bucket: YnVja2V0
  sessionToken:
  accessKeyIdSecret:
    name: copy-stac-asset-s3-secret
    key: access_key_id
  secretAccessKeySecret:
    name: copy-stac-asset-s3-secret
    key: secret_access_key
  regionSecret:
    name: copy-stac-asset-s3-secret
    key: region
  sessionTokenSecret:
    name: copy-stac-asset-s3-secret
    key: session_token
  dataBucketSecret:
    name: copy-stac-asset-s3-secret
    key: data_bucket

minio:
  service:
    endpoint: minio.default:9000
    accessKeyIdSecret:
      name: minio-secret
      key: access_key_id
    secretAccessKeySecret:
      name: minio-secret
      key: secret_access_key
    bucketName: swoop

serviceAccountName: argo
mirrorWorkflowServiceAccountName: argo
copyAssetsTemplateTaskServiceAccountName: argo
publishTemplateTaskServiceAccountName: argo
