{{- if .Values.storage.retainPersistentVolume -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    {{- include "postgres.labels" . | nindent 6 }}
  name: postgres-retain
provisioner: {{ .Values.storage.provisioner }}
reclaimPolicy: Retain
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
{{- end }}
