apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "postgres.labels" . | nindent 6 }}
  name: postgres
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      {{- include "postgres.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres
    spec:
      containers:
        - env:
            - name: PGDATABASE
              value: {{ .Values.postgres.service.dbName }}
            - name: PGAUTHMETHOD
              value: {{ .Values.postgres.service.authMethod }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pg_password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: pg_user
            - name: PGSSLMODE
              value: {{ .Values.postgres.service.sslMode }}
            - name: PGAUTHMETHOD
              value: {{ .Values.postgres.service.authMethod }}
            - name: SWOOP_DB_SCHEMA_VERSION_TABLE
              value: {{ .Values.postgres.service.schemaVersionTable }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          name: {{ .Values.postgres.deployment.name }}
          ports:
            - containerPort: {{ .Values.postgres.container.port }}
          resources: {}
          volumeMounts:
            - mountPath: /swoop
              name: postgres-claim0
          workingDir: /swoop
      restartPolicy: Always
      volumes:
        - name: postgres-claim0
          persistentVolumeClaim:
            claimName: postgres-claim0
status: {}
