# Default values for swoop-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: quay.io/minio/minio
  tag: latest
container:
  port: 9000
  servicePort: 9001
service:
  type: ClusterIP
  port: 9000
  targetPort: 9000
  servicePort: 9001
  serviceTargetPort: 9001
  name: minio
  bucketName: swoop
  accessKeyIdSecret:
    name: minio-secret
    key: access_key_id
  secretAccessKeySecret:
    name: minio-secret
    key: secret_access_key
  accessKeyId: bWluaW8=
  secretAccessKey: cGFzc3dvcmQ=
  endpoint: http://minio.default:9000
deployment:
  name: minio
replicaCount: 1
