# Default values for swoop-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

local-path-provisioner:
  enabled: true
  singleNamespace: true
  storageClass:
    provisionerName: filmdrop.io/local-minio-path-provisioner
    name: local-path-class-minio
  configmap:
    name: local-path-config-minio

image:
  repository: quay.io/minio/minio
  tag: latest
container:
  port: 9000
  servicePort: 9001
service:
  type: ClusterIP
  port: 9000
  targetPort: 9000
  servicePort: 9001
  serviceTargetPort: 9001
  name: minio
  bucketName: swoop
  createSecret: true
  accessKeyIdSecret:
    name: minio-secret
    key: access_key_id
  secretAccessKeySecret:
    name: minio-secret
    key: secret_access_key
  accessKeyId: bWluaW8=
  secretAccessKey: cGFzc3dvcmQ=
  endpoint: http://minio.default:9000
storage:
  size: 256M
  volumeBindingMode: WaitForFirstConsumer
  provisioner: filmdrop.io/local-minio-path-provisioner
  retainPersistentVolume: true
  storageClassName: minio-retain
deployment:
  name: minio
replicaCount: 1
