# Default values for swoop-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

postgres:
  service:
    port: 5432
    name: postgres
    dbName: swoop
    dbHost: postgres.default
    apiRoleUsername: c3dvb3BfYXBp
    apiRolePassword: cGFzc19hcGk=
    createApiRoleSecret: true
    apiRoleUsernameSecret:
      name: swoop-api-pg-secret
      key: username
    apiRolePasswordSecret:
      name: swoop-api-pg-secret
      key: password
    sslMode: disable
    authMethod: trust
    schemaVersionTable: swoop.schema_version
  migration:
    enabled: false
    imagePullPolicy: Always
    jobName: migration-job
    version: 8
    no_wait: false
    rollback: false
    image:
      repository: quay.io/element84/swoop-db
      tag: latest

minio:
  service:
    port: 9000
    name: minio
    bucketName: swoop
    accessKeyId: bWluaW8=
    secretAccessKey: cGFzc3dvcmQ=
    createSecret: true
    endpoint: http://minio.default:9000
    accessKeyIdSecret:
      name: swoop-caboose-minio-secret
      key: access_key_id
    secretAccessKeySecret:
      name: swoop-caboose-minio-secret
      key: secret_access_key

image:
  repository: quay.io/element84/swoop
  tag: latest
container:
  port: 8000
service:
  type: ClusterIP
  port: 8000
  targetPort: 8000
  executionDir: s3://swoop/execution
  configFile: workflow-config.yml
  name: swoop-api
  serviceAccount: swoop-api
deployment:
  name: swoop-api
replicaCount: 1
