# Default values for swoop-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

postgres:
  create: true
  image:
    repository: quay.io/element84/swoop-pgdbmate
    tag: latest
  container:
    port: 5432
  service:
    port: 5439
    targetPort: 5432
    name: postgres
    dbName: swoop
    authMethod: trust
  deployment:
    name: postgres
  replicaCount: 1

minio:
  create: true
  image:
    repository: quay.io/minio/minio
    tag: latest
  container:
    port: 9000
    servicePort: 9001
  service:
    port: 9000
    targetPort: 9000
    servicePort: 9001
    serviceTargetPort: 9001
    name: minio
    bucketName: swoop
  deployment:
    name: minio
  replicaCount: 1

swoopApi:
  image:
    repository: quay.io/element84/swoop
    tag: latest
  container:
    port: 8000
  service:
    port: 8000
    targetPort: 8000
    swoopExecutionDir: s3://swoop/execution
    swoopS3Endpoint: http://minio:9000
    swoopWorkflowConfigFile: workflow-config.yml
    name: swoop-api
  deployment:
    name: swoop-api
  replicaCount: 1
