apiVersion: v1
kind: Secret
metadata:
  name: swoop-caboose-pg-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.cabooseRoleUsername }}
  password: {{ .Values.postgres.service.cabooseRolePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: swoop-caboose-minio-secret
type: Opaque
data:
  access_key_id: {{ .Values.minio.service.accessKeyId }}
  secret_access_key: {{ .Values.minio.service.secretAccessKey }}
