apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
{{- $stacApiEndpoint := .Values.service.stacApiEndpoint -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "stac")  }}
    {{- if (hasKey .Values.global.stac "endpoint")  }}
      {{- $stacApiEndpoint := .Values.global.stac.endpoint -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
  swoop-config.yaml: |
    handlers:
      argoHandler:
        type: argoWorkflows
        argoConf:
          k8sOptions:
            configOverrides:
              context:
                namespace: {{ .Release.Namespace | quote }}

      publishStacItemHandler:
        type: synchttp
        parameters:
          feature:
            type: object
            required:
              - collection
            properties:
              collection:
                type: string
        request:
          url: {{ $stacApiEndpoint }}/collections/{{`{{ .parameters.feature.collection }}`}}/items
          method: POST
          body: "{{`{{ .parameters.feature }}`}}"
          headers:
            Content-Type: "application/json"
          followRedirects: true
          responses:
            - statusCode: 400
              message: ".*timeout.*"
              result: error
            - statusCode: 404
              result: fatal

    conductors:
      main:
        handlers:
          - argoHandler
          - stacItemHandler

    callbacks:
      publishStacItem: &callbacksPublishStacItem
        handler: publishStacItemHandler
        type: perFeature
        when:
          - "successful"
        parameters:
          feature:
            path: .feature
        enabled: true

    workflows:
      mirror:
        description: "A workflow to copy STAC items into a local mirror"
        version: 2
        handler: argoHandler
        argoOpts:
          template: workflowtemplate/mirror-workflow
        cacheKeyHashIncludes:
          - .features[].id
          - .features[].collection
        cacheKeyHashExcludes: []
        callbacks:
          publishStacItem:
            <<: *callbacksPublishStacItem
