{{- $dbCreateSecret := .Values.postgres.service.createCabooseRoleSecret -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "service")  }}
      {{- if (hasKey .Values.global.postgres.service "createCabooseRoleSecret")  }}
        {{- $dbCreateSecret = .Values.global.postgres.service.createCabooseRoleSecret -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $dbCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-caboose-pg-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.cabooseRoleUsername }}
  password: {{ .Values.postgres.service.cabooseRolePassword }}
{{- end }}
