{{- if .Values.swoopCaboose.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
     {{- include "swoop-caboose.labels" . | nindent 6 }}
  name: swoop-caboose
spec:
  replicas: {{ .Values.swoopCaboose.replicaCount }}
  selector:
    matchLabels:
      {{- include "swoop-caboose.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: swoop-caboose
    spec:
      serviceAccountName: {{ .Values.swoopCaboose.serviceAccount }}
      containers:
        - env:
            - name: PGDATABASE
              value: {{ .Values.postgres.service.dbName }}
            - name: PGHOST
              value: {{ .Values.postgres.service.name }}
            - name: PGPORT
              value: "{{ .Values.postgres.service.port }}"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: swoop-caboose-secret
                  key: pg_password
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: swoop-caboose-secret
                  key: pg_user
            - name: PGSSLMODE
              value: {{ .Values.postgres.service.sslMode }}
            - name: PGAUTHMETHOD
              value: {{ .Values.postgres.service.authMethod }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: swoop-caboose-secret
                  key: minio_access_key_id
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: swoop-caboose-secret
                  key: minio_secret_access_key
            - name: SWOOP_S3_BUCKET
              value: {{ .Values.minio.service.bucketName }}
            - name: SWOOP_S3_ENDPOINT
              value: {{ .Values.swoopCaboose.service.swoopS3Endpoint }}
            - name: SWOOP_CONFIG_FILE
              value: {{ .Values.swoopCaboose.service.swoopConfigFile }}
          image:  "{{ .Values.swoopCaboose.image.repository }}:{{ .Values.swoopCaboose.image.tag }}"
          name: {{ .Values.swoopCaboose.deployment.name }}
          command: ["swoop", "caboose", "argo"]
          ports:
            - containerPort: {{ .Values.swoopCaboose.container.port }}
          resources: {}
      restartPolicy: Always
status: {}
{{- end }}
