{{- if .Values.service.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  access_key_id: {{ .Values.service.accessKeyId }}
  secret_access_key: {{ .Values.service.secretAccessKey }}
{{- end }}
