{{- if .Values.storage.retainPersistentVolume -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    {{- include "minio.labels" . | nindent 6 }}
  name: minio-retain
provisioner: {{ .Values.storage.provisioner }}
reclaimPolicy: Retain
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
{{- if (hasKey .Values.storage "parameters")  }}
{{- if (hasKey .Values.storage.parameters "type")  }}
parameters:
  type: {{ .Values.storage.parameters.type }}
{{- end -}}
{{- end -}}
{{- end }}
