apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  swoop_access_key_id: {{ .Values.minio.service.accessKeyId }}
  swoop_secret_access_key: {{ .Values.minio.service.secretAccessKey }}
