{{- $dbCreateSecret := .Values.postgres.service.createOwnerRoleSecret -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "service")  }}
      {{- if (hasKey .Values.global.postgres.service "createOwnerRoleSecret")  }}
        {{- $dbCreateSecret = .Values.global.postgres.service.createOwnerRoleSecret -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $dbCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-migration-role-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.ownerRoleUsername }}
  password: {{ .Values.postgres.service.ownerRolePassword }}
{{- end }}
