apiVersion: v1
kind: Secret
metadata:
  name: pg-migration-role-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.ownerRoleUsername }}
  password: {{ .Values.postgres.service.ownerRolePassword }}
