{{- if .Values.postgres.migration.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.swoopApi.serviceAccount }}
  namespace: {{ .Values.swoopApi.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.swoopApi.serviceAccount }}-migration-reader
rules:
rules:
- apiGroups:
  - '*'
  resources:
  - statefulsets
  - services
  - replicationcontrollers
  - replicasets
  - podtemplates
  - podsecuritypolicies
  - pods
  - pods/log
  - pods/exec
  - podpreset
  - poddisruptionbudget
  - persistentvolumes
  - persistentvolumeclaims
  - jobs
  - endpoints
  - deployments
  - deployments/scale
  - daemonsets
  - cronjobs
  - configmaps
  - namespaces
  - events
  - secrets
  verbs:
  - create
  - get
  - watch
  - delete
  - list
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.swoopApi.serviceAccount }}-migration-reader
subjects:
- kind: ServiceAccount
  name: {{ .Values.swoopApi.serviceAccount }}
roleRef:
  kind: Role
  name: {{ .Values.swoopApi.serviceAccount }}-migration-reader
  apiGroup: rbac.authorization.k8s.io
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
