apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "swoop-api.labels" . | nindent 6 }}
  name: {{ .Values.swoopApi.service.name }}
spec:
  type: {{ .Values.swoopApi.service.type }}
  ports:
    - name: "{{ .Values.swoopApi.service.targetPort }}"
      port: {{ .Values.swoopApi.service.port }}
      targetPort: {{ .Values.swoopApi.service.targetPort }}
  selector:
    {{- include "swoop-api.labels" . | nindent 6 }}
status:
  loadBalancer: {}
