apiVersion: v1
kind: Secret
metadata:
  name: swoop-api-secret
type: Opaque
data:
  pg_user: cG9zdGdyZXM=
  pg_password: cGFzc3dvcmQ=
  swoop_access_key_id: bWluaW8=
  swoop_secret_access_key: cGFzc3dvcmQ=
