apiVersion: v1
kind: Secret
metadata:
  name: swoop-api-pg-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.apiRoleUsername }}
  password: {{ .Values.postgres.service.apiRolePassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: swoop-api-minio-secret
type: Opaque
data:
  access_key_id: {{ .Values.minio.service.accessKeyId }}
  secret_access_key: {{ .Values.minio.service.secretAccessKey }}
