apiVersion: v1
kind: Secret
metadata:
  name: swoop-api-secret
type: Opaque
data:
  pg_user: {{ .Values.postgres.service.dbUser }}
  pg_password: {{ .Values.postgres.service.dbPassword }}
  swoop_access_key_id: {{ .Values.minio.service.accessKeyId }}
  swoop_secret_access_key: {{ .Values.minio.service.secretAccessKey }}
