{{- $dbCreateSecret := .Values.postgres.service.createApiRoleSecret -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "service")  }}
      {{- if (hasKey .Values.global.postgres.service "createApiRoleSecret")  }}
        {{- $dbCreateSecret = .Values.global.postgres.service.createApiRoleSecret -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $dbCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: swoop-api-pg-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.apiRoleUsername }}
  password: {{ .Values.postgres.service.apiRolePassword }}
{{- end }}
