apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
     {{- include "swoop-api.labels" . | nindent 6 }}
  name: swoop-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "swoop-api.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: swoop-api
    spec:
# Start of variable mappings
{{- $migrationEnabled := .Values.postgres.migration.enabled -}}
{{- $migrationPullPolicy := .Values.postgres.migration.imagePullPolicy -}}
{{- $migrationServiceAccount := .Values.service.serviceAccount -}}
{{- $migrationjobName := .Values.postgres.migration.jobName  -}}
{{- $migrationVersion := .Values.postgres.migration.version -}}
{{- $dbName := .Values.postgres.service.dbName -}}
{{- $dbHost := .Values.postgres.service.dbHost -}}
{{- $dbPasswordSecretName := .Values.postgres.service.apiRolePasswordSecret.name -}}
{{- $dbPasswordSecretKey := .Values.postgres.service.apiRolePasswordSecret.key -}}
{{- $dbUsernameSecretName := .Values.postgres.service.apiRoleUsernameSecret.name -}}
{{- $dbUsernameSecretKey := .Values.postgres.service.apiRoleUsernameSecret.key -}}
{{- $dbSSLMode := .Values.postgres.service.sslMode -}}
{{- $dbAuthMethod := .Values.postgres.service.authMethod -}}
{{- $dbSchemaVersionTable := .Values.postgres.service.schemaVersionTable -}}
{{- $s3BucketName := .Values.minio.service.bucketName -}}
{{- $s3Endpoint := .Values.minio.service.endpoint -}}
{{- $s3AccessKeyIdSecretName := .Values.minio.service.accessKeyIdSecret.name -}}
{{- $s3AccessKeyIdSecretKey := .Values.minio.service.accessKeyIdSecret.key -}}
{{- $s3SecretAccessKeySecretName := .Values.minio.service.secretAccessKeySecret.name -}}
{{- $s3SecretAccessKeySecretKey := .Values.minio.service.secretAccessKeySecret.key -}}
{{- $swoopConfigFile := .Values.service.configFile -}}
{{- $swoopExecutionDir := .Values.service.executionDir -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "migration")  }}
      {{- if (hasKey .Values.global.postgres.migration "enabled")  }}
        {{- $migrationEnabled = .Values.global.postgres.migration.enabled -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.migration "imagePullPolicy")  }}
        {{- $migrationPullPolicy = .Values.global.postgres.migration.imagePullPolicy -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.migration "jobName")  }}
        {{- $migrationjobName = .Values.global.postgres.migration.jobName -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.migration "version")  }}
        {{- $migrationVersion = .Values.global.postgres.migration.version -}}
      {{- end -}}
    {{- end -}}
    {{- if (hasKey .Values.global.postgres "service")  }}
      {{- if (hasKey .Values.global.postgres.service "dbName")  }}
        {{- $dbName = .Values.global.postgres.service.dbName -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.service "dbHost")  }}
        {{- $dbHost = .Values.global.postgres.service.dbHost -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.service "apiRolePasswordSecret")  }}
        {{- if (hasKey .Values.global.postgres.service.apiRolePasswordSecret "name")  }}
          {{- $dbPasswordSecretName = .Values.global.postgres.service.apiRolePasswordSecret.name -}}
        {{- end -}}
        {{- if (hasKey .Values.global.postgres.service.apiRolePasswordSecret "key")  }}
          {{- $dbPasswordSecretKey = .Values.global.postgres.service.apiRolePasswordSecret.key -}}
        {{- end -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.service "apiRoleUsernameSecret")  }}
        {{- if (hasKey .Values.global.postgres.service.apiRoleUsernameSecret "name")  }}
          {{- $dbUsernameSecretName = .Values.global.postgres.service.apiRoleUsernameSecret.name -}}
        {{- end -}}
        {{- if (hasKey .Values.global.postgres.service.apiRoleUsernameSecret "key")  }}
          {{- $dbUsernameSecretKey = .Values.global.postgres.service.apiRoleUsernameSecret.key -}}
        {{- end -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.service "sslMode")  }}
        {{- $dbSSLMode = .Values.global.postgres.service.sslMode -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.service "authMethod")  }}
        {{- $dbAuthMethod = .Values.global.postgres.service.authMethod -}}
      {{- end -}}
      {{- if (hasKey .Values.global.postgres.service "schemaVersionTable")  }}
        {{- $dbSchemaVersionTable = .Values.global.postgres.service.schemaVersionTable -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- if (hasKey .Values.global "minio")  }}
    {{- if (hasKey .Values.global.minio "service")  }}
      {{- if (hasKey .Values.global.minio.service "bucketName")  }}
        {{- $s3BucketName = .Values.global.minio.service.bucketName -}}
      {{- end -}}
      {{- if (hasKey .Values.global.minio.service "endpoint")  }}
        {{- $s3Endpoint = .Values.global.minio.service.endpoint -}}
      {{- end -}}
      {{- if (hasKey .Values.global.minio.service "accessKeyIdSecret")  }}
        {{- if (hasKey .Values.global.minio.service.accessKeyIdSecret "name")  }}
          {{- $s3AccessKeyIdSecretName = .Values.global.minio.service.accessKeyIdSecret.name -}}
        {{- end -}}
        {{- if (hasKey .Values.global.minio.service.accessKeyIdSecret "key")  }}
          {{- $s3AccessKeyIdSecretKey = .Values.global.minio.service.accessKeyIdSecret.key -}}
        {{- end -}}
      {{- end -}}
      {{- if (hasKey .Values.global.minio.service "secretAccessKeySecret")  }}
        {{- if (hasKey .Values.global.minio.service.secretAccessKeySecret "name")  }}
          {{- $s3SecretAccessKeySecretName = .Values.global.minio.service.secretAccessKeySecret.name -}}
        {{- end -}}
        {{- if (hasKey .Values.global.minio.service.secretAccessKeySecret "key")  }}
          {{- $s3SecretAccessKeySecretKey = .Values.global.minio.service.secretAccessKeySecret.key -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
  {{- if (hasKey .Values.global "swoop")  }}
    {{- if (hasKey .Values.global.swoop "api")  }}
      {{- if (hasKey .Values.global.swoop.api "serviceAccount")  }}
        {{- $migrationServiceAccount = .Values.global.swoop.api.serviceAccount -}}
      {{- end -}}
      {{- if (hasKey .Values.global.swoop.api "configFile")  }}
        {{- $swoopConfigFile := .Values.global.swoop.api.configFile -}}
      {{- end -}}
      {{- if (hasKey .Values.global.swoop.api "executionDir")  }}
        {{- $swoopExecutionDir := .Values.global.swoop.api.executionDir -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
# End of global variable mappings
    {{ if $migrationEnabled }}
      serviceAccountName: {{ $migrationServiceAccount }}
      initContainers:
        - name: wait-for-db-migration
          image: ghcr.io/groundnuty/k8s-wait-for:v2.0
          imagePullPolicy: {{ $migrationPullPolicy }}
          args:
            - "job"
            - "{{ $migrationjobName }}-{{ $migrationVersion }}"
    {{ end }}
      containers:
        - env:
            - name: PGDATABASE
              value: {{ $dbName }}
            - name: PGHOST
              value:  {{ $dbHost }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $dbPasswordSecretName }}
                  key: {{ $dbPasswordSecretKey }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ $dbUsernameSecretName }}
                  key: {{ $dbUsernameSecretKey }}
            - name: PGSSLMODE
              value: {{ $dbSSLMode }}
            - name: PGAUTHMETHOD
              value: {{ $dbAuthMethod }}
            - name: SWOOP_DB_SCHEMA_VERSION_TABLE
              value: {{ $dbSchemaVersionTable }}
            - name: SWOOP_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ $s3AccessKeyIdSecretName }}
                  key: {{ $s3AccessKeyIdSecretKey }}
            - name: SWOOP_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $s3SecretAccessKeySecretName }}
                  key: {{ $s3SecretAccessKeySecretKey }}
            - name: SWOOP_BUCKET_NAME
              value: {{ $s3BucketName }}
            - name: SWOOP_EXECUTION_DIR
              value: {{ $swoopExecutionDir }}
            - name: SWOOP_S3_ENDPOINT
              value: {{ $s3Endpoint }}
            - name: SWOOP_WORKFLOW_CONFIG_FILE
              value: {{ $swoopConfigFile }}
          image:  "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.deployment.name }}
          ports:
            - containerPort: {{ .Values.container.port }}
          resources: {}
      restartPolicy: Always
status: {}
