apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    {{- include "pgstac.labels" . | nindent 6 }}
  name: {{ .Values.pgStac.service.name }}
spec:
  ports:
    - name: "5439"
      port: {{ .Values.pgStac.service.port }}
      targetPort: {{ .Values.pgStac.service.targetPort }}
  selector:
    {{- include "pgstac.labels" . | nindent 6 }}
status:
  loadBalancer: {}
