{{- if .Values.pgStac.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    {{- include "pgstac.labels" . | nindent 6 }}
  name: pgstac
spec:
  replicas: {{ .Values.pgStac.replicaCount }}
  selector:
    matchLabels:
      {{- include "pgstac.labels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pgstac
    spec:
      containers:
        - args:
            - postgres
            - -N
            - "500"
          env:
            - name: PGDATABASE
              value: {{.Values.pgStac.dbName}}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgStac.passwordSecret.name }}
                  key: {{ .Values.pgStac.passwordSecret.key }}
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgStac.userNameSecret.name }}
                  key: {{ .Values.pgStac.userNameSecret.key }}
            - name: POSTGRES_DB
              value: {{.Values.pgStac.dbName}}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgStac.passwordSecret.name }}
                  key: {{ .Values.pgStac.passwordSecret.key }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pgStac.userNameSecret.name }}
                  key: {{ .Values.pgStac.userNameSecret.key }}
          image: "{{ .Values.pgStac.image.repository }}:{{ .Values.pgStac.image.tag }}"
          name: {{ .Values.pgStac.deployment.name }}
          ports:
            - containerPort: {{ .Values.pgStac.container.port }}
          resources: {}
          volumeMounts:
            - mountPath: /pgstac
              name: pgstac-claim0
          workingDir: /pgstac
      restartPolicy: Always
      volumes:
        - name: pgstac-claim0
          persistentVolumeClaim:
            claimName: pgstac-claim0
status: {}
{{- end }}
