{{- if .Values.pgStac.createPgStacSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: stac-fastapi-secret
type: Opaque
data:
  username: {{ .Values.pgStac.dbUser }}
  password: {{ .Values.pgStac.dbPassword }}
{{- end }}
