apiVersion: v1
kind: Secret
metadata:
  name: stac-fastapi-secret
type: Opaque
data:
  img_dbname: cG9zdGdpcw==
  img_hostrw: cGdzdGFj
  img_password: cGFzc3dvcmQ=
  img_username: dXNlcm5hbWU=
  pg_dbname: cG9zdGdpcw==
  pg_password: cGFzc3dvcmQ=
  pg_username: dXNlcm5hbWU=