apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  # name is required; we should never have an execution with this name
  name: mirror-workflow
  labels:
    workflow-name: mirror-workflow
spec:
# Start of variable mappings
{{- $serviceAccountName := .Values.mirrorWorkflowServiceAccountName -}}
# End of global variable mappings
  entrypoint: workflow
  serviceAccountName: {{ $serviceAccountName }} # set this so the proper permissions are assigned
  templates:
    - name: workflow
      dag:
        tasks:
          - name: copy-assets
            templateRef:
              name: copy-assets-template
              template: copy-task
            arguments:
              artifacts:
                - name: input
                  path: /mnt/input.json
                  s3:
                    key: "executions/{{`{{workflow.name}}`}}/input.json"
          - name: publish
            dependencies: [copy-assets]
            templateRef:
              name: publish-template
              template: publish
            arguments:
              artifacts:
              - name: input
                from: "{{`{{tasks.copy-assets.outputs.artifacts.output}}`}}"

