{{- if .Values.s3.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: copy-stac-asset-s3-secret
type: Opaque
data:
  access_key_id: {{ .Values.s3.accessKeyId }}
  secret_access_key: {{ .Values.s3.secretAccessKey }}
  region: {{ .Values.s3.region }}
  session_token: {{ .Values.s3.sessionToken }}
  data_bucket: {{ .Values.s3.data_bucket }}

{{- end }}
