{{- $dbCreateSecret := .Values.postgres.service.createDBAdminSecret -}}
{{- if (hasKey .Values "global")  }}
  {{- if (hasKey .Values.global "postgres")  }}
    {{- if (hasKey .Values.global.postgres "service")  }}
      {{- if (hasKey .Values.global.postgres.service "createDBAdminSecret")  }}
        {{- $dbCreateSecret = .Values.global.postgres.service.createDBAdminSecret -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
{{- if $dbCreateSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: pg-admin-role-secret
type: Opaque
data:
  username: {{ .Values.postgres.service.dbUser }}
  password: {{ .Values.postgres.service.dbPassword }}
{{- end }}
