# This workflow sets up Testkube Kubernetes Tests

name: Testkube Kubernetes Tests

on:
  push:
    branches: ["main" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  testkube:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Create k3d Cluster
        uses: nolar/setup-k3d-k3s@v1
        with:
          k3d-args: --no-lb

      - name: Configuring kube context and getting cluster info
        run: |
          export KUBECONFIG=${HOME}/.kube/config
          kubectl cluster-info
          kubectl get pods -n kube-system
          kubectl get nodes
          echo "kubeconfig-file-location:" $KUBECONFIG
          echo "current-context:" $(kubectl config current-context)
          export KUBE_CONFIG_CONTEXT=$(kubectl config current-context)
          echo "kubernetes_config_file=\"$KUBECONFIG\"" >> min.tfvars
          echo "kubernetes_config_context=\"$KUBE_CONFIG_CONTEXT\"" >> min.tfvars

      - name: Install MinIO Helm Chart
        id: minio_install
        run: helm install minio ./charts/minio/

      - name: Install Postgres Helm Chart
        id: postgres_install
        run: helm install postgres ./charts/postgres/

      - name: Install SWOOP API Helm Chart
        id: swoop_install
        run: helm install swoop-api ./charts/swoop-api/

      - name: Waiting for SWOOP pods
        run: |
          kubectl wait --for=condition=ready --timeout=30m pod -l app=postgres
          kubectl wait --for=condition=ready --timeout=30m pod -l app=minio
          kubectl wait --for=condition=ready --timeout=30m pod -l app=swoop-api

      - name: Checkout swoop repo
        uses: actions/checkout@master
        with:
          repository: Element84/swoop
          path: swoop

      - name: Setup MinIO
        run: |
          kubectl port-forward svc/minio 9000:9000 &
          curl https://dl.min.io/client/mc/release/linux-amd64/mc \
            --create-dirs \
            -o $HOME/minio-binaries/mc
          chmod +x $HOME/minio-binaries/mc
          export PATH=$PATH:$HOME/minio-binaries/
          export MINIO_ACCESS_KEY=`helm get values minio -a -o json | jq -r .minio.service.accessKeyId | base64 --decode`
          export MINIO_SECRET_KEY=`helm get values minio -a -o json | jq -r .minio.service.secretAccessKey | base64 --decode`
          mc alias set swoopminio http://127.0.0.1:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
          mc cp --recursive swoop/tests/fixtures/io/base_01/ swoopminio/swoop/execution/2595f2da-81a6-423c-84db-935e6791046e/

      - name: Checkout swoop-db repo
        uses: actions/checkout@master
        with:
          repository: Element84/swoop-db
          ref: v0.1.3
          path: swoop-db

      - name: Setup Postgres
        run: |
          kubectl port-forward svc/postgres 5432:5432 &
          sudo apt update
          sudo apt install postgresql postgresql-contrib
          export PGHOST="127.0.0.1"
          export PGUSER="`helm get values postgres -a -o json | jq -r .postgres.service.dbUser | base64 --decode`"
          export PGPASSWORD="`helm get values postgres -a -o json | jq -r .postgres.service.dbPassword | base64 --decode`"
          export PGPORT="`helm get values postgres -a -o json | jq -r .postgres.service.port`"
          export PGDATABASE="`helm get values postgres -a -o json | jq -r .postgres.service.dbName`"
          export PGAUTHMETHOD="trust"
          psql -p $PGPORT -U $PGUSER $PGDATABASE  < swoop-db/src/swoop/db/migrations/00000_base_schema.up.sql
          psql -p $PGPORT -U $PGUSER $PGDATABASE  < swoop-db/src/swoop/db/fixtures/base_01.sql

      - name: Installing Testkube
        run: |
          wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add -
          echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install -y testkube
          helm repo add kubeshop https://kubeshop.github.io/helm-charts ; helm repo update && helm upgrade --install --reuse-values --create-namespace testkube kubeshop/testkube --set testkube-api.cloud.key=${{ secrets.TESTKUBE_CLOUD_KEY }} --set testkube-api.cloud.orgId=${{ secrets.TESTKUBE_ORG_ID }} --set testkube-api.cloud.envId=${{ secrets.TESTKUBE_ENV_ID }} --set testkube-api.minio.enabled=false --set mongodb.enabled=false --set testkube-dashboard.enabled=false --set testkube-api.cloud.url=agent.testkube.io:443 --namespace testkube
          kubectl wait --for=condition=ready --timeout=30m pod -n testkube -l app.kubernetes.io/instance=testkube

      - name: Create Testkube Tests
        continue-on-error: true
        run: |
          testkube create test --namespace testkube --name swoop-api-root-test --type curl/test --test-content-type git-file --git-uri https://github.com/Element84/swoop-testkube.git --git-branch main --git-path tests/curl/swoop-api-root-test.json --variable apiHost=swoop-api.default:8000
          testkube create test --namespace testkube --name swoop-api-jobs-test --type curl/test --test-content-type git-file --git-uri https://github.com/Element84/swoop-testkube.git --git-branch main --git-path tests/curl/swoop-api-jobs-test.json --variable apiHost=swoop-api.default:8000
          testkube create test --namespace testkube --name swoop-api-payload-input-test --type curl/test --test-content-type git-file --git-uri https://github.com/Element84/swoop-testkube.git --git-branch main --git-path tests/curl/swoop-api-payload-input-test.json --variable apiHost=swoop-api.default:8000
          testkube create test --namespace testkube --name swoop-api-simple-k6-load-test --type k6/script --test-content-type git-file --git-uri https://github.com/Element84/swoop-testkube.git --git-branch main --git-path tests/k6/swoop-api-simple-k6-load-test.js --variable API_HOST=swoop-api.default:8000

      - name: Running Testkube Tests
        run: |
          testkube run test --watch swoop-api-root-test
          testkube run test --watch swoop-api-jobs-test
          testkube run test --watch swoop-api-payload-input-test
          testkube run test --watch swoop-api-simple-k6-load-test
